apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: shubham
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shubham
  template:
    metadata:
      labels:
        app: shubham
    spec:
      containers:
      - name: shubham
        image: image_name
        ports:
        - containerPort: 80
       
---

apiVersion: v1
kind: Service
metadata:
  name: shubham-service
spec:
  type: NodePort
  selector:
    app: shubham
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
